// MOVIES
export const GET_MOVIES_START = "GET_MOVIES_START";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";

// MOVIE DETAILS
export const GET_MOVIE_DETAILS_START = "GET_MOVIE_DETAILS_START";
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
